### ISSUE TITLE
Not updating remote plugins

### ISSUE THREAD

**Issue by mhartington** [vimlab/mdown.vim#1]
Looks like you _need_ to include the node-host plugin in order for this plugin to get registered with neovim's remote plugin agin. This means adding an additional plugin.

``` viml
  Plug 'neovim/node-host', {'do': 'npm install'}
  Plug 'vimlab/mdown.vim', {'do': 'npm install'}
```

**Comment by mklabs** [comment]
Hi @mhartington very true. I used to include it in my vimfiles folder but I would be keen to include it in mdown as well.

Thanks for the feedback.

**Comment by mklabs** [comment]
Actually, I'll just update the readme documentation. Thanks again.
